### ISSUE TITLE
search on new site is non-functional

### ISSUE THREAD

**Issue by Gambloide** [fyne-io/docs.fyne.io#5]
The search-bar on the new site does nothing.
You can input text but that is it.
Neither pressing enter/return nor pressing the icon in the search bar does anything.

I tested it in Firefox 123.0b4 (64-bit) and Chrome 121.0.6167.140 (Official Build) (64-bit).

**Comment by andydotxyz** [comment]
There was a temporary issue that should be resolved a couple of ours ago. Sorry I didn't see this message before.

**Comment by sdassow** [comment]
This is actually still an issue - now the dropdown opens and items can be clicked on, but the full text search still isn't functional. I was using it a lot in the past and miss it dearly now.

**Comment by andydotxyz** [comment]
That sounds like a separate issue given that the OP states "non-functional".

Just to try and understand - are you saying it works on titles but not on the body text?

**Comment by sdassow** [comment]
> That sounds like a separate issue given that the OP states "non-functional".

It seemed like that before since my search query didn't give any results (forgot what it was). But...

> Just to try and understand - are you saying it works on titles but not on the body text?

This appears to be the case. Searching for "package" only shows "Organisation and Packages" in the dropdown, but not "Packaging for Desktop" for example.

**Comment by andydotxyz** [comment]
Should all be fixed now :)

**Comment by sdassow** [comment]
This looks better and I'll leave this issue for now as it's clearly functional. But I'll open another one since the full text search aspect still isn't fully solved as far as I can tell.
